// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mrwgrxycaismmetsjqhd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1yd2dyeHljYWlzbW1ldHNqcWhkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYzMzg0NzksImV4cCI6MjA2MTkxNDQ3OX0.iU5ftD8EBagRT9rZYfLNAB3o55zQAKR6H1Z1qkRqNxY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);